### ISSUE TITLE
Setup CI to run all Python and JS tests

### ISSUE THREAD

**Issue by edouard-lopez** [Coaxis-ASP/opt#17]
**related:** #8 
Actuellement, seul les tests du front-end du front-office sont exécutés. 

Il est difficile de voir si une pull request ou un commit provoque des régression dans le reste de l'application.

**Todo:**
* [x] tests python backoffice
* [x] tests JS backoffice
* [x] tests python frontoffice
* [x] tests JS frontoffice
* [x] tests bash

**Comment by edouard-lopez** [comment]
close by #8
